graph TD
    indukcja_matematyczna["Indukcja matematyczna<br/>(sem 1)"]
    logika_podstawowa["Logika podstawowa (and, or, not, kwantyfikatory)<br/>(sem 1)"]
    funkcje_matematyczne["Funkcje - typy i własności<br/>(sem 1)"]
    zbiory["Zbiory i operacje na zbiorach<br/>(sem 1)"]
    relacje["Relacje i relacje równoważności<br/>(sem 1)"]
    zbiory --> relacje
    porzadki["Porządki (częściowe, liniowe)<br/>(sem 1)"]
    relacje --> porzadki
    indukcja_matematyczna --> porzadki
    git_github["Git i GitHub<br/>(sem 1)"]
    dobre_praktyki_kodu["Zasady dobrego programowania<br/>(sem 1)"]
    debugowanie["Debugowanie (GDB, IDE)<br/>(sem 1)"]
    podstawy_programowania --> debugowanie
    testowanie["Testowanie (jednostkowe, frameworki)<br/>(sem 1)"]
    podstawy_programowania --> testowanie
    podstawy_unix["Podstawy systemu UNIX<br/>(sem 1)"]
    bash_komendy["Podstawowe komendy bash<br/>(sem 1)"]
    podstawy_unix --> bash_komendy
    skrypty_bash["Proste skrypty bashowe<br/>(sem 1)"]
    bash_komendy --> skrypty_bash
    podstawy_programowania["Podstawy programowania (funkcje, programy)<br/>(sem 1)"]
    funkcje_programowanie["Funkcje w programowaniu<br/>(sem 1)"]
    podstawy_programowania --> funkcje_programowanie
    funkcje_matematyczne --> funkcje_programowanie
    dowodzenie_poprawnosci["Dowodzenie poprawności programów (niezmienniki pętli)<br/>(sem 1)"]
    indukcja_matematyczna --> dowodzenie_poprawnosci
    logika_podstawowa --> dowodzenie_poprawnosci
    tablice["Tablice<br/>(sem 1)"]
    podstawy_programowania --> tablice
    wektory_euklidesowe["Wektory w przestrzeniach euklidesowych<br/>(sem 1)"]
    iloczyn_skalarny["Iloczyn skalarny i geometria wektorów<br/>(sem 1)"]
    wektory_euklidesowe --> iloczyn_skalarny
    niezaleznosc_liniowa["Liniowa niezależność i bazy<br/>(sem 1)"]
    wektory_euklidesowe --> niezaleznosc_liniowa
    ciagi_granice["Ciągi i granice<br/>(sem 1)"]
    szeregi["Szeregi liczbowe<br/>(sem 1)"]
    ciagi_granice --> szeregi
    ciaglość_funkcji["Ciągłość funkcji<br/>(sem 1)"]
    ciagi_granice --> ciaglość_funkcji
    pochodne["Pochodne funkcji jednej zmiennej<br/>(sem 1)"]
    ciaglość_funkcji --> pochodne
    ekstrema_1d["Ekstrema funkcji jednej zmiennej<br/>(sem 1)"]
    pochodne --> ekstrema_1d
    calki["Całki Riemanna<br/>(sem 1)"]
    pochodne --> calki
    rekurencja["Rekurencja i równania rekurencyjne<br/>(sem 2)"]
    indukcja_matematyczna --> rekurencja
    funkcje_programowanie --> rekurencja
    kombinatoryka["Kombinatoryka (wariacje, permutacje)<br/>(sem 2)"]
    indukcja_matematyczna --> kombinatoryka
    notacja_asymptotyczna["Notacja asymptotyczna i złożoność<br/>(sem 2)"]
    funkcje_matematyczne --> notacja_asymptotyczna
    ciagi_granice --> notacja_asymptotyczna
    zlozonosc_algorytmow["Analiza złożoności algorytmów<br/>(sem 2)"]
    notacja_asymptotyczna --> zlozonosc_algorytmow
    rekurencja --> zlozonosc_algorytmow
